"""Adiciona coluna cta_url à tabela Campaign

Revision ID: 5b5c09ce1a81
Revises: a2b78383c19c
Create Date: 2025-11-17 18:35:15.979187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5c09ce1a81'
down_revision = 'a2b78383c19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_url', sa.String(length=500), nullable=False, server_default='https://example.com'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('cta_url')

    # ### end Alembic commands ###
